name: Model Training

on:
  schedule:
    - cron: '0 0 30 * *'  # Runs on the last day of the month
  workflow_dispatch:  # Allows manual triggering

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train the model
        run: |
          python src/train_model.py