name: Model Training

on:
  schedule:
    - cron: '0 0 30 * *'  # Runs on the last day of the month
  workflow_dispatch:  # Allows manual triggering

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --extra-index-url https://pypi.org/simple

      - name: Train model with cross-validation
        run: python train_model.py

      - name: Train final model
        run: python train_final_model.py

      - name: Predict for next month
        run: python predict.py
